# Generated by Django 4.1.7 on 2023-06-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0051_all_leads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_leads',
        ),
    ]
