# Generated by Django 4.1.7 on 2023-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0053_all_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_leads',
            name='data_manager_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='all_leads',
            name='telecaller_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
